### ISSUE TITLE
Can't upload

### ISSUE THREAD

**Issue by rolik2001** [balena-io-projects/balena-sound#8]
![image](https://user-images.githubusercontent.com/20404966/61188269-5943fd80-a685-11e9-8f9a-7e6e4aea7bcc.png)

I have tried to upload from different os, Ubuntu 16.04, 18.04 and Windows 10.

**Comment by chrisys** [comment]
The error you have been getting looks to be because we had a requirement for the alsa-base package which is no longer present in the latest version of the base images. We have just released a new version of balenaSound with this removed so if you download v0.0.8 and try pushing again you should be good to go!
